# Generated by Django 5.1.5 on 2025-02-03 19:00

import shop.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='shop/images', validators=[shop.validators.validate_image_size]),
        ),
    ]
